INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES
(NULL, NULL, NULL, NULL, NULL), (NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL), (NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL), (NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL), (NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL), (NULL, NULL, NULL, NULL, NULL);

INSERT INTO users (name, age) VALUES
(NULL, NULL), (NULL, NULL), (NULL, NULL), (NULL, NULL), (NULL, NULL),
(NULL, NULL), (NULL, NULL), (NULL, NULL), (NULL, NULL), (NULL, NULL),
(NULL, NULL), (NULL, NULL), (NULL, NULL), (NULL, NULL), (NULL, NULL),
(NULL, NULL), (NULL, NULL), (NULL, NULL), (NULL, NULL), (NULL, NULL);
